AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 30
Description: Yo-yaku kun summarize
Resources:
  SUMMARIZE:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://slack-app-nlp-yo-yaku-kun-summmarize/86457079a92cad9cca772246ed77aab9
      Handler: index.handler
      Runtime: nodejs8.10
      Layers:
      - arn:aws:lambda:ap-northeast-1:782623905234:layer:SharedLayer:1
