AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 30
Description: Yo-yaku kun summarize
Resources:
  SUMMARIZE:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://slack-app-nlp-yo-yaku-kun-summmarize/e71b0cf61955f72ad2e9dcbaec821099
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        API:
          Type: Api
          Properties:
            Path: /summarize
            Method: post
