AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 30
Description: 'Yo-Yaku kun api'
Resources:
  HelloSAM:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../built/dev_practice
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        API:
          Type: Api
          Properties:
            Path: /summarize
            Method: post
      Environment:
        Variables:
          SLACK_TOKEN: !Ref SlackToken
          SLACK_CHANEL: !Ref SlackChanel
Parameters:
  SlackToken:
    Type: String
  SlackChanel:
    Type: String