AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SharedLayer
      Description: kuromoji dictionary
      ContentUri: 's3://slack-app-nlp-yo-yaku-kun-module/node_modules.zip'
      CompatibleRuntimes:
        - nodejs6.10
        - nodejs8.10
      LicenseInfo: 'Available under the MIT-0 license.'
Outputs:
  LayerVersionArn:
    Value: !Ref SharedLayer